// Generated by using torchexport::export() -> do not edit by hand
#include "torchsparse/torchsparse.h"
#include <lantern/types.h>
void * p_torchsparse_last_error = NULL;

TORCHSPARSE_API void* torchsparse_last_error()
{
  return p_torchsparse_last_error;
}

TORCHSPARSE_API void torchsparse_last_error_clear()
{
  p_torchsparse_last_error = NULL;
}

torch::Tensor d_sigmoid (torch::Tensor z);
TORCHSPARSE_API void* _d_sigmoid (void* z) {
  try {
    return  make_raw::Tensor(d_sigmoid(from_raw::Tensor(z)));
  } TORCHSPARSE_HANDLE_EXCEPTION
  return (void*) NULL;
}
