// Generated by using torchexport::export() -> do not edit by hand
#ifdef _WIN32
#ifndef TORCHSPARSE_HEADERS_ONLY
#define TORCHSPARSE_API extern "C" __declspec(dllexport)
#else
#define TORCHSPARSE_API extern "C" __declspec(dllimport)
#endif
#else
#define TORCHSPARSE_API extern "C"
#endif

#ifndef TORCHSPARSE_HANDLE_EXCEPTION
#define TORCHSPARSE_HANDLE_EXCEPTION                                  \
catch(const std::exception& ex) {                                  \
  p_torchsparse_last_error = make_raw::string(ex.what());             \
} catch (std::string& ex) {                                        \
  p_torchsparse_last_error = make_raw::string(ex);                    \
} catch (...) {                                                    \
  p_torchsparse_last_error = make_raw::string("Unknown error. ");     \
}
#endif

void host_exception_handler ();
extern void* p_torchsparse_last_error;
TORCHSPARSE_API void* torchsparse_last_error ();
TORCHSPARSE_API void torchsparse_last_error_clear();

TORCHSPARSE_API void* _sparse_ind2ptr (void* ind, int64_t M);
TORCHSPARSE_API void* _sparse_ptr2ind (void* ptr, int64_t E);
TORCHSPARSE_API void* _sparse_random_walk (void* rowptr, void* col, void* start, int64_t walk_length);

#ifdef RCPP_VERSION
inline void* sparse_ind2ptr (void* ind, int64_t M) {
  auto ret =  _sparse_ind2ptr(ind, M);
  host_exception_handler();
  return ret;
}
inline void* sparse_ptr2ind (void* ptr, int64_t E) {
  auto ret =  _sparse_ptr2ind(ptr, E);
  host_exception_handler();
  return ret;
}
inline void* sparse_random_walk (void* rowptr, void* col, void* start, int64_t walk_length) {
  auto ret =  _sparse_random_walk(rowptr, col, start, walk_length);
  host_exception_handler();
  return ret;
}
#endif // RCPP_VERSION
