// Generated by using torchexport::export() -> do not edit by hand
#ifdef _WIN32
#ifndef TORCHSPARSE_HEADERS_ONLY
#define TORCHSPARSE_API extern "C" __declspec(dllexport)
#else
#define TORCHSPARSE_API extern "C" __declspec(dllimport)
#endif
#else
#define TORCHSPARSE_API extern "C"
#endif

#ifndef TORCHSPARSE_HANDLE_EXCEPTION
#define TORCHSPARSE_HANDLE_EXCEPTION                                  \
catch(const std::exception& ex) {                                  \
  p_torchsparse_last_error = make_raw::string(ex.what());             \
} catch (std::string& ex) {                                        \
  p_torchsparse_last_error = make_raw::string(ex);                    \
} catch (...) {                                                    \
  p_torchsparse_last_error = make_raw::string("Unknown error. ");     \
}
#endif

void host_exception_handler ();
extern void* p_torchsparse_last_error;
TORCHSPARSE_API void* torchsparse_last_error ();
TORCHSPARSE_API void torchsparse_last_error_clear();

TORCHSPARSE_API void* _d_sigmoid (void* z);

#ifdef RCPP_VERSION
inline void* d_sigmoid (void* z) {
  auto ret =  _d_sigmoid(z);
  host_exception_handler();
  return ret;
}
#endif // RCPP_VERSION
