// Generated by using torchexport::export() -> do not edit by hand
#include <Rcpp.h>
#include <torch.h>
#define TORCHSPARSE_HEADERS_ONLY
#include <torchsparse/torchsparse.h>

// [[Rcpp::export]]
torch::Tensor rcpp_sparse_ind2ptr (torch::Tensor ind, int64_t M) {
  return  sparse_ind2ptr(ind.get(), M);
}
