# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_sparse_ind2ptr <- function(ind, M) {
    .Call('_torchsparse_rcpp_sparse_ind2ptr', PACKAGE = 'torchsparse', ind, M)
}

rcpp_sparse_ptr2ind <- function(ptr, E) {
    .Call('_torchsparse_rcpp_sparse_ptr2ind', PACKAGE = 'torchsparse', ptr, E)
}

rcpp_sparse_partition <- function(rowptr, col, optional_value, num_parts, recursive) {
    .Call('_torchsparse_rcpp_sparse_partition', PACKAGE = 'torchsparse', rowptr, col, optional_value, num_parts, recursive)
}

rcpp_sparse_partition2 <- function(rowptr, col, optional_value, optional_node_weight, num_parts, recursive) {
    .Call('_torchsparse_rcpp_sparse_partition2', PACKAGE = 'torchsparse', rowptr, col, optional_value, optional_node_weight, num_parts, recursive)
}

rcpp_sparse_mt_partition <- function(rowptr, col, optional_value, optional_node_weight, num_parts, recursive, num_workers) {
    .Call('_torchsparse_rcpp_sparse_mt_partition', PACKAGE = 'torchsparse', rowptr, col, optional_value, optional_node_weight, num_parts, recursive, num_workers)
}

rcpp_sparse_relabel <- function(col, idx) {
    .Call('_torchsparse_rcpp_sparse_relabel', PACKAGE = 'torchsparse', col, idx)
}

rcpp_sparse_random_walk <- function(rowptr, col, start, walk_length) {
    .Call('_torchsparse_rcpp_sparse_random_walk', PACKAGE = 'torchsparse', rowptr, col, start, walk_length)
}

rcpp_sparse_spmm_sum <- function(opt_row, rowptr, col, opt_value, opt_colptr, opt_csr2csc, mat) {
    .Call('_torchsparse_rcpp_sparse_spmm_sum', PACKAGE = 'torchsparse', opt_row, rowptr, col, opt_value, opt_colptr, opt_csr2csc, mat)
}

rcpp_sparse_spmm_mean <- function(opt_row, rowptr, col, opt_value, opt_rowcount, opt_colptr, opt_csr2csc, mat) {
    .Call('_torchsparse_rcpp_sparse_spmm_mean', PACKAGE = 'torchsparse', opt_row, rowptr, col, opt_value, opt_rowcount, opt_colptr, opt_csr2csc, mat)
}

rcpp_sparse_spmm_min <- function(rowptr, col, opt_value, mat) {
    .Call('_torchsparse_rcpp_sparse_spmm_min', PACKAGE = 'torchsparse', rowptr, col, opt_value, mat)
}

rcpp_sparse_spmm_max <- function(rowptr, col, opt_value, mat) {
    .Call('_torchsparse_rcpp_sparse_spmm_max', PACKAGE = 'torchsparse', rowptr, col, opt_value, mat)
}

rcpp_sparse_spspmm_sum <- function(rowptrA, colA, optional_valueA, rowptrB, colB, optional_valueB, K) {
    .Call('_torchsparse_rcpp_sparse_spspmm_sum', PACKAGE = 'torchsparse', rowptrA, colA, optional_valueA, rowptrB, colB, optional_valueB, K)
}

rcpp_delete_tensor_pair <- function(x) {
    invisible(.Call('_torchsparse_rcpp_delete_tensor_pair', PACKAGE = 'torchsparse', x))
}

rcpp_tensor_pair_get_first <- function(x) {
    .Call('_torchsparse_rcpp_tensor_pair_get_first', PACKAGE = 'torchsparse', x)
}

rcpp_tensor_pair_get_second <- function(x) {
    .Call('_torchsparse_rcpp_tensor_pair_get_second', PACKAGE = 'torchsparse', x)
}

rcpp_delete_tensor_tensor_optionaltensor <- function(x) {
    invisible(.Call('_torchsparse_rcpp_delete_tensor_tensor_optionaltensor', PACKAGE = 'torchsparse', x))
}

rcpp_tensor_tensor_optionaltensor_get_first <- function(x) {
    .Call('_torchsparse_rcpp_tensor_tensor_optionaltensor_get_first', PACKAGE = 'torchsparse', x)
}

rcpp_tensor_tensor_optionaltensor_get_second <- function(x) {
    .Call('_torchsparse_rcpp_tensor_tensor_optionaltensor_get_second', PACKAGE = 'torchsparse', x)
}

rcpp_tensor_tensor_optionaltensor_get_third <- function(x) {
    .Call('_torchsparse_rcpp_tensor_tensor_optionaltensor_get_third', PACKAGE = 'torchsparse', x)
}

rcpp_delete_tensor_tensor_optionaltensor_tensor <- function(x) {
    invisible(.Call('_torchsparse_rcpp_delete_tensor_tensor_optionaltensor_tensor', PACKAGE = 'torchsparse', x))
}

rcpp_tensor_tensor_optionaltensor_tensor_get_first <- function(x) {
    .Call('_torchsparse_rcpp_tensor_tensor_optionaltensor_tensor_get_first', PACKAGE = 'torchsparse', x)
}

rcpp_tensor_tensor_optionaltensor_tensor_get_second <- function(x) {
    .Call('_torchsparse_rcpp_tensor_tensor_optionaltensor_tensor_get_second', PACKAGE = 'torchsparse', x)
}

rcpp_tensor_tensor_optionaltensor_tensor_get_third <- function(x) {
    .Call('_torchsparse_rcpp_tensor_tensor_optionaltensor_tensor_get_third', PACKAGE = 'torchsparse', x)
}

rcpp_tensor_tensor_optionaltensor_tensor_get_fourth <- function(x) {
    .Call('_torchsparse_rcpp_tensor_tensor_optionaltensor_tensor_get_fourth', PACKAGE = 'torchsparse', x)
}

