# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_sparse_ind2ptr <- function(ind, M) {
    .Call('_torchsparse_rcpp_sparse_ind2ptr', PACKAGE = 'torchsparse', ind, M)
}

rcpp_sparse_ptr2ind <- function(ptr, E) {
    .Call('_torchsparse_rcpp_sparse_ptr2ind', PACKAGE = 'torchsparse', ptr, E)
}

